Partners
citi-onboarding/tenis-center pull request #4
Opened 2022-05-31 18:03 UTC by emillycn

## What I did

- Model
- Controller
 -Routes

## How to test

1. Open the terminal and go to the folder of this project

1. In terminal:
   1. `git checkout develop`
   1. `git pull`
   1. `git checkout <branch name>`
   1. `git pull origin <branch name>`
   1. `yarn install`
   1. `code .`
   1. `sudo docker-compose up`
   1. `yarn typeorm migration:run`
   1. `yarn start`
1. In your browser go to http://localhost:3000/<route>

1. In VScode open `<relative path>`

1. Things to do during the code:

   - Open insomnia and postbird to test the requisitions needed

1. Read the changed files section on GitHub

1. Test the things that you think are worth testing, even the ones that are not in this description

&nbsp;

---

2022-06-03 12:19 UTC, claraabk requested changes
nice job! just a small change: on the model the primaryGeneratorColumn is supossed to be an id, so you have to create another column for image

2022-06-05 15:12 UTC, fernandesbarreto approved these changes

2022-06-06 15:32 UTC, thaisnevest approved these changes

2022-06-06 17:45 UTC, claraabk approved these changes
nice job! congrats

2022-06-06 17:45 UTC, merged